image: node:10
clone:
  depth: full
pipelines:
  branches:
    develop:
      - step:
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_DEV.git HEAD:master -f
